### ISSUE TITLE
Different background colour for editable cells

### ISSUE THREAD

**Issue by Wolfy7** [untitled-team-101/sudoku#10]
At the moment its not visible which cells are editable if you already insert a value:
![grafik](https://user-images.githubusercontent.com/16044116/135830235-07e6ae85-bba5-4eb1-ba38-458a8104d028.png)

Possible solution:
Set different background colours for editable cells.

**Comment by ThisIsFaar** [comment]
can I work on this?

> At the moment its not visible which cells are editable if you already insert a value: ![grafik](https://user-images.githubusercontent.com/16044116/135830235-07e6ae85-bba5-4eb1-ba38-458a8104d028.png)
> 
> Possible solution: Set different background colours for editable cells.

**Comment by ThisIsFaar** [comment]
can I work on this?
