### ISSUE TITLE
Need Issue Template

### ISSUE THREAD

**Issue by tanmayVaish** [untitled-team-101/sudoku#18]
Make 2 Issue Template for Bug Report and Feature Request!

**Comment by Aron-R** [comment]
Hey there, I can try and do this if you’d like ^-^

**Comment by tanmayVaish** [comment]
@Aron-R ok done!! I have assigned you! Send PR, Good luck!

**Comment by Aron-R** [comment]
@tanmayVaish 
Thank you ❤️
Is there any specifics you have in mind that I should know before I do it?

**Comment by tanmayVaish** [comment]
@Aron-R Just create a basic one. Or if you want, you can study our repo and add repo specific things!

**Comment by Aron-R** [comment]
@tanmayVaish Thank you for the input ^-^
