### ISSUE TITLE
Toggle for In-game music.

### ISSUE THREAD

**Issue by tanmayVaish** [untitled-team-101/sudoku#3]
Right now, we cannot mute the music played during the game. We need a **toggle** to switch music on and off.

**Comment by kushalShukla-web** [comment]
may i work on this?

**Comment by tanmayVaish** [comment]
@kushalShukla-web You are now assigned. Good Luck and send us a PR.

**Comment by jahgath** [comment]
Can I work on this as well ?

**Comment by tanmayVaish** [comment]
@jahgath Right now it is assigned to @kushalShukla-web , If he will not do it, we will assign you then!! Till then, you can watch for some other issues we have, or create some new ones.

**Comment by kushalShukla-web** [comment]
okay..

**Comment by kushalShukla-web** [comment]
@tanmayVaish could you pls tell  me what packages i needed here to run this whole code .
coz there is no installation process is given here ....

**Comment by kushalShukla-web** [comment]
i just do npm install and then npm start but local host 3000 is not starting

**Comment by tanmayVaish** [comment]
> i just do npm install and then npm start but local host 3000 is not starting

   ```     "framer-motion": "^4.1.17",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-router": "^5.2.0",
        "react-router-dom": "^5.2.0",
        "react-scripts": "4.0.3",
        "sass": "^1.36.0" 
```

You can also check them in ```package.json```!!

**Comment by tanmayVaish** [comment]
@jahgath You can team up with @kushalShukla-web , if he wants, You guys can then collaborate over it.
