### ISSUE TITLE
Page overflowing in 2nd "How To Play" page

### ISSUE THREAD

**Issue by tanmayVaish** [untitled-team-101/sudoku#4]
2nd "How To Play" page is not supposed to be scrolled down. Adjust the page so that it could not be scrolled down.

**Preview**
_Look at the bottom right (There is scroll down space left)_

![image](https://user-images.githubusercontent.com/55585498/135798288-759349ea-aa27-45e4-98cd-83f80743efa1.png)

**Comment by nayanbari** [comment]
@tanmayVaish I would like to fix this issue. Will you assign this to me?

**Comment by anishsaraogi** [comment]
I can work on this issue, please assign it to me, @tanmayVaish

**Comment by Shubh-2402** [comment]
@tanmayVaish  i would love to work on this issue,plz assign it to me

**Comment by tanmayVaish** [comment]
@nayanbari @anishsaraogi @Shubh-2402  A PR has already been made to fix this issue. I am closing this issue.
