### ISSUE TITLE
Need Modals instead of Prompts

### ISSUE THREAD

**Issue by tanmayVaish** [untitled-team-101/sudoku#5]
Right now, we are having same old boring browser prompts like these:

**Preview**
_This one is after you win first game_

![image](https://user-images.githubusercontent.com/55585498/135801890-b361229f-2229-4083-a5f6-f019cbfb88d1.png)

Design and create modals for all events like these. Just stick to base UI of the whole game (like the colors etc) for the design.

**Comment by alammoiz** [comment]
I would love to do this task, Please assign it to me @tanmayVaish

**Comment by tanmayVaish** [comment]
@alammoiz Done! Send us a PR! Good Luck!

**Comment by alammoiz** [comment]
> @alammoiz Done! Send us a PR! Good Luck!

https://github.com/untitled-team-101/sudoku/pull/15

Please review this
<img width="1537" alt="Screenshot 2021-10-04 at 5 07 56 PM" src="https://user-images.githubusercontent.com/24625561/135852320-70924aac-4bf4-4bae-9552-0aa9129e0154.png">

**Comment by Raghav-Modani** [comment]
Is the issue resolved or still open? I would like to work on it.
