### ISSUE TITLE
On-screen button for removing the number from a cell

### ISSUE THREAD

**Issue by kubikill** [untitled-team-101/sudoku#7]
Right now, removing numbers from a cell can be done by pressing Backspace on the keyboard, however there is no way to do this with just a mouse or touchscreen since there's no on-screen button for that. I'd love to work on this if possible.

**Comment by tanmayVaish** [comment]
@kubikill Go for it !! Good luck! 

But do let us know where are you planning to insert the button for that.

**Comment by kubikill** [comment]
Thanks! 

> But do let us know where are you planning to insert the button for that.

I plan to insert it on the right side of the screen, just below the "9" button.
